[package]
name = "rust_xml_example"
version = "0.1.0"
authors = ["AnaTofuZ <anatofuz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.20.0"
